//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesNet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoesEntities : DbContext
    {
        public ShoesEntities()
            : base("name=ShoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Заказ> Заказ { get; set; }
        public DbSet<Пользователи> Пользователи { get; set; }
        public DbSet<ПунктВыдачи> ПунктВыдачи { get; set; }
        public DbSet<СоставЗаказ> СоставЗаказ { get; set; }
        public DbSet<Товар> Товар { get; set; }
    }
}
