//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public Заказ()
        {
            this.СоставЗаказ = new HashSet<СоставЗаказ>();
        }
    
        public int НомерЗаказа { get; set; }
        public string ДатаЗаказа { get; set; }
        public string ДатаДоставки { get; set; }
        public int КодАдресПунктВыдачи { get; set; }
        public int КодПользователя { get; set; }
        public string КодДляПолучения { get; set; }
        public string СтатусЗаказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктВыдачи ПунктВыдачи { get; set; }
        public virtual ICollection<СоставЗаказ> СоставЗаказ { get; set; }
    }
}
