//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПунктВыдачи
    {
        public ПунктВыдачи()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Код { get; set; }
        public string Индекс { get; set; }
        public string Адрес { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
