//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказ
    {
        public int Код { get; set; }
        public int КодЗаказа { get; set; }
        public string Артикул { get; set; }
        public Nullable<int> Колчество { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
