//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.СоставЗаказ = new HashSet<СоставЗаказ>();
        }
    
        public string Артикул { get; set; }
        public string НаименованиеТовара { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string КатегорияТовара { get; set; }
        public Nullable<int> ДействующаяСкидка { get; set; }
        public Nullable<int> КолВоНаСкладе { get; set; }
        public string ОписаниеТовара { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<СоставЗаказ> СоставЗаказ { get; set; }
    }
}
